### ISSUE TITLE
guzzlehttp version conflict

### ISSUE THREAD

**Issue by justdick** [digikraaft/laravel-paystack-webhooks#1]
i require and updated version of guzzle http in my project but this package require older version, thereby creating conflicts. 
this is the response i get 
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires digikraaft/laravel-paystack-webhooks ^1.1 -> satisfiable by digikraaft/laravel-paystack-webhooks[v1.1.0].
    - digikraaft/laravel-paystack-webhooks v1.1.0 requires guzzlehttp/guzzle ^6.5 -> found guzzlehttp/guzzle[6.5.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.3).

Installation failed, reverting ./composer.json to its original content.`

**Comment by timoladoyinbo** [comment]
Hello @justdick yes there will be a conflict with the newer guzzle version. I would try and push an update today to address this. If you however can't wait till then, feel free to do a pull request of this.

Cheers.

**Comment by timoladoyinbo** [comment]
Hello, @justdick I've pushed a new release [v1.2.0](https://github.com/digikraaft/laravel-paystack-webhooks/tree/v1.2.0) that supports Guzzle 7.3
