### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by ObsidianBlaze** [digikraaft/laravel-paystack-webhooks#2]
Hi team, I noticed that you can not install this package on a Laravel version 8.75😢

**Comment by timoladoyinbo** [comment]
Hi @ObsidianBlaze the latest version doesn't but a [previous version (1.3.0)](https://github.com/digikraaft/laravel-paystack-webhooks/releases/tag/v1.3.0) does. You can install this in your Laravel 8 project using `composer require digikraaft/laravel-paystack-webhooks:1.3.0`

Let me know if this works for you.

**Comment by ObsidianBlaze** [comment]
I'd give it a try and revert right away.

**Comment by ObsidianBlaze** [comment]
Works like a charm, thanks for the speedy response.
