### ISSUE TITLE
Inheriting WebhooksControllerfrom Digikraaft returns a 403 Forbidden error.

### ISSUE THREAD

**Issue by ObsidianBlaze** [digikraaft/laravel-paystack-webhooks#3]
Hello team,

I hope this gets resolved soon.

Whenever a request is made on a class with an inheritance from the WebhooksController class inside of the Digikraaft package, it always returns a 403 forbidden error. 

The error is not as descriptive making it seemingly impossible to debug what the problem could be. 

I'd be on the lookout for some assistance in resolving this issue.
![Screenshot (220)](https://user-images.githubusercontent.com/42479950/190935448-3e8635db-6453-44d5-88b3-37fa204bdc15.png)

**Comment by timoladoyinbo** [comment]
Hi @ObsidianBlaze the package automatically verifies that webhooks are coming from Paystack (https://github.com/digikraaft/laravel-paystack-webhooks#verifying-webhook-signatures) so you may want to confirm that you're using the correct Paystack credentials.
