### ISSUE TITLE
Demo request

### ISSUE THREAD

**Issue by ljsharp** [digikraaft/laravel-paystack-webhooks#4]
Sorry there is no issue but I want to ask if you have a demo or an example for us to follow. Thanks for this amazing package :)

**Comment by timoladoyinbo** [comment]
Hi @ljsharp you can have a look at this [demo](https://github.com/digikraaft/laravel-paystack-subscription-demo) from another package which uses this package.

**Comment by ljsharp** [comment]
Thank you so much @timoladoyinbo

**Comment by ljsharp** [comment]
Please Sir, it is for paystack subscription. I want a demo that use paystack webhooks. Sorry I did not mention it earlier.

**Comment by timoladoyinbo** [comment]
Read my last message well. The subscription package uses the web hooks package. You will see how it is used in the demo (which I linked above) of the subscription package

Regards,
Tim.

**Comment by ljsharp** [comment]
Alright thanks!
